name: Python Unit Test

inputs:
  pyproject_toml_dir:
    description: 'Do a build and verify'
    required: true
    default: '.'
  debug_mode:
    description: "Debug Mode"
    required: false
    default: 'false'

permissions:
  contents: read

runs:
  using: 'composite'
  steps:
    - name: Test with pytest
      env:
        DEBUG_MODE: ${{ inputs.debug_mode == 'true' }}
        PYPROJECT_TOML_DIR: ${{ inputs.pyproject_toml_dir }}
      shell: bash
      run: |
        cd ${PYPROJECT_TOML_DIR}
        if ${DEBUG_MODE}; then
          pytest -rP
        else
          pytest -rx
        fi