# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches:
      - "main"
  workflow_dispatch:
    inputs:
      run_all_tests:
        required: false
        default: 'false'
        options:
          - true
          - false
      debug_mode:
        description: "Debug Mode"
        type: choice
        required: true
        default: 'false'
        options:
          - true
          - false
    branches: 
      - "**"
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - "main"
    paths-ignore:
      - '**.md'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Get all the changed files
      id: changed-files
      uses: tj-actions/changed-files@v44.5.7
      # To compare changes between the current commit and the last pushed remote commit set `since_last_remote_commit: true`. e.g
      with:
        since_last_remote_commit: true
    - name: Test with pytest
      uses: ./.github/workflows/unit_testing/python/
      with:
        pyproject_toml_dir: "."